MODULE TESTING_MODULE
  IMPLICIT NONE
CONTAINS
  FUNCTION TESTFUNC(Z) RESULT(RES)
    IMPLICIT NONE
    COMPLEX(KIND=8) :: Z,RES
    print *, Z
    RES = Z + (1.2200000000000, -3.21)
    RETURN
  END FUNCTION TESTFUNC
END MODULE TESTING_MODULE